#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define PT_SIZE 72 /* sizeof(struct pt_regs)	# */
#define PT_FP 0 /* offsetof(struct pt_regs, fp)	# */
#define PT_SP 4 /* offsetof(struct pt_regs, sp)	# */
#define PT_R0 8 /* offsetof(struct pt_regs, r0)	# */
#define PT_R1 12 /* offsetof(struct pt_regs, r1)	# */
#define PT_R2 16 /* offsetof(struct pt_regs, r2)	# */
#define PT_R3 20 /* offsetof(struct pt_regs, r3)	# */
#define PT_R4 24 /* offsetof(struct pt_regs, r4)	# */
#define PT_R5 28 /* offsetof(struct pt_regs, r5)	# */
#define PT_R6 32 /* offsetof(struct pt_regs, r6)	# */
#define PT_R7 36 /* offsetof(struct pt_regs, r7)	# */
#define PT_R8 40 /* offsetof(struct pt_regs, r8)	# */
#define PT_R9 44 /* offsetof(struct pt_regs, r9)	# */
#define PT_R10 48 /* offsetof(struct pt_regs, r10)	# */
#define PT_R11 52 /* offsetof(struct pt_regs, r11)	# */
#define PT_R12 56 /* offsetof(struct pt_regs, r12)	# */
#define PT_R13 60 /* offsetof(struct pt_regs, r13)	# */
#define PT_PC 64 /* offsetof(struct pt_regs, pc)	# */
#define PT_MODE 68 /* offsetof(struct pt_regs, pt_mode)	# */

#define PT_TEXT_ADDR 73 /* sizeof(struct pt_regs) + 1	# */
#define PT_TEXT_LEN 74 /* sizeof(struct pt_regs) + 2	# */
#define PT_DATA_ADDR 75 /* sizeof(struct pt_regs) + 3	# */

#define TS_THREAD_INFO 4 /* offsetof(struct task_struct, stack)	# */
#define TI_TASK 0 /* offsetof(struct thread_info, task)	# */
#define TI_FLAGS 8 /* offsetof(struct thread_info, flags)	# */
#define TI_ADDR_LIMIT 24 /* offsetof(struct thread_info, addr_limit)	# */
#define TI_CPU_CONTEXT 60 /* offsetof(struct thread_info, cpu_context)	# */

#define CC_FP 0 /* offsetof(struct cpu_context, fp)	# */
#define CC_SP 4 /* offsetof(struct cpu_context, sp)	# */
#define CC_R0 8 /* offsetof(struct cpu_context, r0)	# */
#define CC_R1 12 /* offsetof(struct cpu_context, r1)	# */
#define CC_R2 16 /* offsetof(struct cpu_context, r2)	# */
#define CC_R3 20 /* offsetof(struct cpu_context, r3)	# */
#define CC_R4 24 /* offsetof(struct cpu_context, r4)	# */
#define CC_R5 28 /* offsetof(struct cpu_context, r5)	# */
#define CC_R6 32 /* offsetof(struct cpu_context, r6)	# */
#define CC_R7 36 /* offsetof(struct cpu_context, r7)	# */
#define CC_R8 40 /* offsetof(struct cpu_context, r8)	# */
#define CC_R9 44 /* offsetof(struct cpu_context, r9)	# */
#define CC_R10 48 /* offsetof(struct cpu_context, r10)	# */
#define CC_R11 52 /* offsetof(struct cpu_context, r11)	# */
#define CC_R12 56 /* offsetof(struct cpu_context, r12)	# */
#define CC_R13 60 /* offsetof(struct cpu_context, r13)	# */
#define CC_PC 64 /* offsetof(struct cpu_context, pc)	# */


#endif
